#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "../include/types.h"
#include "../include/errors.h"
#include "utils.h"
#include "m5_analytics.h"

static int compareSessionLogTimestamp(const void *a, const void *b) {
    const SessionLog *la = a;
    const SessionLog *lb = b;
    return strcmp(la->timestamp, lb->timestamp);
}

int generateReport(const SessionLog *logs, size_t logCount, AnalyticsReport *outReport) {
    if (!logs || !outReport) return ERR_ARG;

    memset(outReport, 0, sizeof(*outReport));
    outReport->reportID = 1;
    outReport->generatedByUserID = 0;
    safe_str_copy(outReport->date, sizeof(outReport->date), "1970-01-01");
    outReport->totalSessions = (int)logCount;

    int freq[256] = {0};
    int totalLen = 0;
    for (size_t i = 0; i < logCount; ++i) {
        const SessionLog *entry = &logs[i];
        if (entry->errorFlag) outReport->totalErrors++;
        const char *src = (entry->mode == 'E') ? entry->inputText : entry->morseOutput;
        for (const char *p = src; *p; ++p) {
            unsigned char uc = (unsigned char)*p;
            if (isprint(uc)) {
                freq[uc]++;
                totalLen++;
            }
        }
    }

    if (logCount > 0) {
        outReport->avgMessageLength = (float)totalLen / (float)logCount;
    }

    int best = 0;
    for (int i = 0; i < 256; ++i) {
        if (freq[i] > best) {
            best = freq[i];
            outReport->mostUsedChar = (char)i;
        }
    }

    if (outReport->mostUsedChar == 0) {
        outReport->mostUsedChar = '-';
    }

    return OK;
}

void printReportSummary(const AnalyticsReport *report, FILE *outStream) {
    if (!report || !outStream) return;

    fprintf(outStream, "Analytics Report:\n");
    fprintf(outStream, "Report ID: %d\n", report->reportID);
    fprintf(outStream, "Generated by user ID: %d\n", report->generatedByUserID);
    fprintf(outStream, "Date: %s\n", report->date);
    fprintf(outStream, "Total sessions: %d\n", report->totalSessions);
    fprintf(outStream, "Most used character: %c\n", report->mostUsedChar);
    fprintf(outStream, "Average message length: %.2f\n", report->avgMessageLength);
    fprintf(outStream, "Total errors: %d\n", report->totalErrors);
}

int exportReportToFile(const AnalyticsReport *report, const char *path) {
    if (!report || !path) return ERR_ARG;
    FILE *f = fopen(path, "w");
    if (!f) return ERR_IO;
    printReportSummary(report, f);
    fclose(f);
    return OK;
}

int getMostUsedCharacter(const SessionLog *logs, size_t logCount, char *outChar) {
    if (!logs || !outChar) return ERR_ARG;
    int freq[256] = {0};
    for (size_t i = 0; i < logCount; ++i) {
        for (const char *p = logs[i].inputText; *p; ++p) {
            unsigned char uc = (unsigned char)*p;
            if (isprint(uc)) freq[uc]++;
        }
    }
    int best = 0;
    for (int i = 0; i < 256; ++i) {
        if (freq[i] > best) {
            best = freq[i];
            *outChar = (char)i;
        }
    }
    return best > 0 ? OK : ERR_NOTFOUND;
}

int sortLogsByDate(SessionLog *logs, size_t logCount) {
    if (!logs) return ERR_ARG;
    qsort(logs, logCount, sizeof(SessionLog), compareSessionLogTimestamp);
    return OK;
}

int searchLogByKeyword(const SessionLog *logs, size_t logCount, const char *keyword, SessionLog *outBuf, size_t *outCount, size_t maxOut) {
    if (!logs || !keyword || !outBuf || !outCount) return ERR_ARG;
    *outCount = 0;
    if (maxOut == 0) return OK;
    for (size_t i = 0; i < logCount && *outCount < maxOut; ++i) {
        if (strstr(logs[i].inputText, keyword) || strstr(logs[i].morseOutput, keyword)) {
            outBuf[*outCount] = logs[i];
            (*outCount)++;
        }
    }
    return OK;
}

float calculateErrorRate(const SessionLog *logs, size_t logCount) {
    if (!logs || logCount == 0) return 0.0f;
    int errors = 0;
    for (size_t i = 0; i < logCount; ++i) {
        if (logs[i].errorFlag) errors++;
    }
    return (float)errors / (float)logCount;
}
